language: php

php:
    - 5.5

before_script:
    - composer install --prefer-dist --no-interaction

script:
    - vendor/bin/phpunit --coverage-clover=clover.xml
    - vendor/bin/phpcs ./src --standard=PSR2 -n

after_success:
    - bash <(curl -s https://codecov.io/bash)
